// flow-typed signature: d75665729b4ef799608984b9a4a86b7e
// flow-typed version: <<STUB>>/jikanjs_v^0.5.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jikanjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
 
declare module 'jikanjs' {
  declare type Season = 'spring' | 'summer' | 'fall' | 'winter';

  declare type AnimeType = 'TV' | 'OVA' | 'ONA' | 'Movie' | 'Special';
  
  declare type LoadSeasonResult = {|
    request_cached: boolean,
    request_hash: string,
    season: Array <{|
      mal_id: number,
      url: string,
      title: string,
      image_url: string,
      type: AnimeType,
    |}>,
    season_name: string,
    season_year: number,
  |};

  declare module.exports: { loadSeason: (year: number, season: Season) => Promise<LoadSeasonResult>};
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jikanjs/lib/jikan' {
  declare module.exports: any;
}

declare module 'jikanjs/test/jikan' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jikanjs/index' {
  declare module.exports: $Exports<'jikanjs'>;
}
declare module 'jikanjs/index.js' {
  declare module.exports: $Exports<'jikanjs'>;
}
declare module 'jikanjs/lib/jikan.js' {
  declare module.exports: $Exports<'jikanjs/lib/jikan'>;
}
declare module 'jikanjs/test/jikan.js' {
  declare module.exports: $Exports<'jikanjs/test/jikan'>;
}
