// flow-typed signature: e0f3615c09968c26f8ed4d4360d5247c
// flow-typed version: <<STUB>>/react-testing-library_v^5.0.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

type GetsAndQueries = {|
  getByTestId: (testID: string) => HTMLElement,
|};

type RenderReturn = GetsAndQueries & {|
  container: HTMLElement,
  baseElement: HTMLElement,
  debug: (baseElement?: HTMLElement) => void,
  rerender: (ui: React$Element<*>) => void,
  unmount: () => boolean,
|};
 
declare module 'react-testing-library' {
  declare module.exports: {
    render: (ui: React$Element<any>, options?: {[string]: *}) => RenderReturn,
  };
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-testing-library/cleanup-after-each' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-testing-library/cleanup-after-each.js' {
  declare module.exports: $Exports<'react-testing-library/cleanup-after-each'>;
}
declare module 'react-testing-library/dist/index.js' {
  declare module.exports: $Exports<'react-testing-library/dist/index'>;
}
