// flow-typed signature: 4ac3bcb1c58ce4d92435e9513e024e71
// flow-typed version: <<STUB>>/snapshot-diff_v^0.4.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snapshot-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snapshot-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snapshot-diff/build/index' {
  declare module.exports: any;
}

declare module 'snapshot-diff/serializer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snapshot-diff/build/index.js' {
  declare module.exports: $Exports<'snapshot-diff/build/index'>;
}
declare module 'snapshot-diff/serializer.js' {
  declare module.exports: $Exports<'snapshot-diff/serializer'>;
}
